# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 主库数据源  #jdbc:postgresql://rm-2ze9a6sc95742n049fo.pg.rds.aliyuncs.com:3432/test_dapeng #jdbc:postgresql://rm-2ze9a6sc95742n049796.pg.rds.aliyuncs.com:3433/test_dapeng
      db1:
        driverClassName: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://rm-2ze9a6sc95742n049fo.pg.rds.aliyuncs.com:3432/test_dapeng
        username: dapeng_pg # root
        password:  EuYhUKyHIhm7YKDq  #
        #                url: jdbc:postgresql://pgm-2zekbc88pzdr3074do.pg.rds.aliyuncs.com:3433/dapeng
        #                username: dapeng_pg # root
        #                password:  EMzWn8ISkHXn41js  #
        initialSize: 5
        minIdle: 10
        maxActive: 300
        maxWait: 600000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        maxEvictableIdleTimeMillis: 900000
        validationQuery: select 'x'     #SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
      # 从库数据源
      db2:
        # 从数据源开关/默认关闭  -开启从库
        driverClassName: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://rm-2ze9a6sc95742n049fo.pg.rds.aliyuncs.com:3432/dapeng #jdbc:postgresql://pgm-2zea6s83lz0wiv259o.pg.rds.aliyuncs.com:3433/postgres
        username:  dapeng_pg #bj_pg_rw
        password:   EuYhUKyHIhm7YKDq #clp3L5iNpVyPW4bw     #
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 300
        # 配置获取连接等待超时的时间
        maxWait: 600000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: select 'x'     #SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
          enabled: true
        statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /monitor/druid/*
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true

#spring:
#    datasource:
#        name: mysql_test
#        type: com.alibaba.druid.pool.DruidDataSource
#        #druid相关配置
#        druid:
#            #监控统计拦截的filters
#            filters: stat
#            driver-class-name: org.postgresql.Driver
#            #基本属性
#            url: jdbc:postgresql://rm-2ze9a6sc95742n049fo.pg.rds.aliyuncs.com:3432/test_dapeng
#            username: dapeng_pg
#            password: EuYhUKyHIhm7YKDq
#            #配置初始化大小/最小/最大
#            initial-size: 1
#            min-idle: 1
#            max-active: 20
#            #获取连接等待超时时间
#            max-wait: 60000
#            #间隔多久进行一次检测，检测需要关闭的空闲连接
#            time-between-eviction-runs-millis: 60000
#            #一个连接在池中最小生存的时间
#            min-evictable-idle-time-millis: 300000
#            validation-query: SELECT 'x'
#            test-while-idle: true
#            test-on-borrow: false
#            test-on-return: false
#            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#            pool-prepared-statements: false
#            max-pool-prepared-statement-per-connection-size: 20